### ISSUE TITLE
Bibtex can truncate macro variable names

### ISSUE THREAD

**Issue by gabrielastro** [pkgw/tex-stuff#12] opened 2019-05-23 14:18 UTC
My `bibtex` truncates lines after a fixed number of characters (e.g. 79), possibly producing `.bbl` files containing (truncating here earlier just for the example!)
```
                       ...\JournalTitle{\ap%
j}, 128, 38}
```
where the command `\apj` obviously should not be truncated. This leads to a compilation-time error. Another possibe outcome of running `bibtex` is
```
                       ...\JournalTitle{\%
apj}, 128, 38}
```
which compiles fine but produces literally "% apj" in the `.pdf` document.

By the way, thank you for this great `.bst` style file!

**Comment by pkgw** [comment] 2019-06-27 21:51
I looked into this a bit, and discovered two things:

1. The way that I was hoping to fix this turns out to not be feasible, I think.
2. My version of bibtex, and probably other recent ones, have a different linebreaking strategy that seems designed to prevent this problem. I can't reproduce it locally.

So I think I will close this and recommend that you see if you can install a newer version of bibtex. If that's not possible, I recommend automating the correction of your output BBL file using the `sed` script described [on this webpage](https://www.volkerschatz.com/tex/advbib.html):

```
:s
/%$/{
  N
  bs
}
s/%\n//g
```

(You'd save that text as something like `fixbbl.sed`, and then run `sed -i -f fixbbl.sed document.bbl`.)

**Closed by pkgw** 2019-06-27 21:51 UTC
